amplitude/redux-query

README.md

The package needs to be built before any examples can be run.
This really tripped me up initially.  Hopefully it helps folks in the future.

Documents the build step when running examples

---

README.md
examples/async/containers/App.js
src/middleware/query.js
test/middlewares/query.test.js

Addresses #3 by allowing users to set `options.headers` in `connectRequest`.

Allow setting headers

---

src/constants/status-codes.js

401 is Unauthorized, so this causes retries against resources the client has been explicitly told it is not authorized to access. HTTP code 408 is Request Timeout

Request timeout is HTTP 408, not 401

---

package.json
src/components/connect-request.js

Hi,
thanks for this awesome library. The library works great with react, but I was not able to use it with react-native due to the react-pure-render dependency. For this reason I replaced the react-pure-render dependency with react-addons-shallow-compare.
All the best,
Martin

Exchange react-pure-render dependency with react-addons-shallow-compare 

---

package.json

Hi,
React is already present as a `peerDependency`, which is good.
We don't need it as an explicit direct dependency.
I'm using React Native 0.43.0-rc.3 which works with React 16.0.0-alpha.3.
So ended up with 2 different React version in my node_modules.
Also I've got another PR coming which itself fixes another issue when you try to use redux-query with React Native. As seen in https://github.com/amplitude/redux-query/issues/32
Let me know what you think.

Moved react from dependencies to devDependencies

---

.npmignore

Hi there
I'm using React Native (0.43.0-rc.3) and initially got the error message reported in https://github.com/amplitude/redux-query/issues/32 when I tried to use redux-query with it.
The reason why it happens is React Native's packager tries to transpile packages in node_modules and if one of the package has a `.babelrc` config, it tries to use it.
Here since I don't have the presets used by redux-query (`"react", "es2015", "stage-2"`) in my main project dependencies, it fails.
One fix is not to ship the `.babelrc` file as part of the npm package so it doesn't confuse RN's packager.
Note that in the future RN will stop transpiling node_modules so this won't be a problem anymore.
See https://github.com/facebook/react-native/issues/10966
Let me know what you think.

Fix error with React Native's Packager

---

src/adapters/superagent.js
test/adapters/superagent.test.js

See #55 for motivation and discussion.

Let superagent handle request body

---

src/middleware/query-advanced.js

Store request controller, rather than its instance

---

docs/principles.md

In Principles page
> Using Angular or Ember? No problem – just don't use react-redux-react.
It should be redux-query-react instead.

Fix typo in the doc

---

packages/redux-query-react/index.d.ts
packages/redux-query/index.d.ts

As our team was exploring integrating redux-query into a new project using TS + React, we discovered the the built in type definitions in redux-query define the "entities state" very loosely, i.e. `type Entities = { [key: string]: any }` which really doesn't provide any time safety for the individual parts of the entities collection.
This PR is my first pass at making most of the types generic in `T`, where `T` is the type of "entities" defined for your particular usage.
With this PR, you might end up w/ something like:
```
interface Notification {
id: string;
name: string;
}
interface EntitiesState {
notificationsById: { [key: string]: Notification }
}
```
And then your *application state*, would be:
```
interface State {
entities: EntitiesState;
queries: QueriesState;
}
```
With these …

Refactor TypeScript to be generic on entities.

---

packages/redux-query/index.d.ts

* Need to put the `TEntities` first in the generic parameters,
so the action generic type can be defaulted properly.

Fix generic defaulting w/ middleware types

---

CHANGELOG.md
README.md
docs/examples/hacker-news.md
docs/examples/simple.md
docs/redux-actions.md
docs/requests-vs-mutations.md
docs/upgrade-guides/v2-to-v3.md
docs/use-requests.md
lerna.json
packages/redux-query-interface-superagent/package.json
packages/redux-query-react/README.md
packages/redux-query-react/flow-test/hooks/use-requests.js
packages/redux-query-react/package.json
packages/redux-query-react/src/components/connect-request.js
packages/redux-query-react/src/hooks/use-memoized-query-configs.js
packages/redux-query-react/src/hooks/use-queries-state.js
packages/redux-query-react/src/hooks/use-request.js
packages/redux-query-react/src/hooks/use-requests.js
packages/redux-query-react/src/index.js
packages/redux-query-react/src/types.js
packages/redux-query-react/test/hooks/use-requests.test.js
packages/redux-query-react/yarn.lock
packages/redux-query/README.md
packages/redux-query/package.json
website/i18n/en.json
website/sidebars.json

`useRequests` is a react hook that takes in an array of query configs and returns two values. The first is an object containing values `isFinished` and `isPending`. `isPending` is true as long as **any** of the network calls made by `useRequests` is still in progress. `isFinished` is false as long **all** requests have not finished. The other value returned is a refresh function. This function when called forces all requests to be recalled no matter the response or status of the previous call.
This is meant to be a replacement to the v2 mapPropsToConfig functionality. Redux Query React did not have a good way of making batch requests in v3. 
This PR mostly copies both the current `useRequest` and v2 `connect-request` to make a hook for an array of query configs. …

Use requests PR

---

packages/redux-query-react/src/components/connect-request.js
packages/redux-query-react/src/hooks/use-requests.js

https://github.com/amplitude/redux-query/issues/158#issuecomment-572334306 fix `finishedCallback` to dismiss console warning:  `Trying to cancel a request that is not in flight:`

fix(redux-query-react): fix finishedCallback

---

packages/redux-query-react/index.d.ts
packages/redux-query-react/yarn.lock

Related #158 
- feat(redux-query-react): Add `useRequests` export and `UseRequests` typing
- fix(redux-query-react): Fix TS errors in `index.d.ts`
- fix(redux-query-react): Query configs should be optional
In `use-request` and `use-requests`, it looks like query configs are a `Maybe` type (to allow ignoring a query) which is useful but wasn't reflected in the TS typings, so I added that.
There are some broken typings that fallback to `any` inside an editor, as seen here:
If you are using TS to consume the package, the build will fail, so I think these should be fixed.

fix(redux-query-react): Add useRequests and fix other typings

---

packages/redux-query-react/index.d.ts
packages/redux-query/index.d.ts

this PR fixes the incompatible type errors in #170 
```typescript
const [, runMutation] = useMutation((id: string) => someConfigFactory(id))
runMutation(1) // should error out because of incompatible types
runMutation('some id') // no errors
```
...plus fixes to action types `RequestSuccess` and `RequestFailure` types.
This is tested on Typescript ver. 3.8.2

Update typescript typings

---

packages/redux-query-react/package.json
packages/redux-query-react/src/hooks/use-queries-state.js
packages/redux-query-react/test/hooks/use-requests.test.js
packages/redux-query-react/yarn.lock
packages/redux-query/index.d.ts
packages/redux-query/package.json
packages/redux-query/src/selectors/query.js
packages/redux-query/src/types.js
packages/redux-query/yarn.lock

By using reselect we can prevent unnecessary churning of components that `useRequests` so they only re-render when the requests they care about change.

Add Reselect + Caching

---

packages/redux-query-react/index.d.ts

this reverts the commit i made removing some definitions for the hooks, causing issues here: https://github.com/amplitude/redux-query/issues/187

Revert "fixes type definitions for useRequest/s, useMutation types"

---

packages/redux-query/index.d.ts

This allows the actions to be correctly matched in our overloaded redux Dispatch type without needing to manually annotate all of our `mutateAsync`s.

Default to using the global Entities type in actions

---

packages/redux-query-react/flow-test/hooks/use-request-on-demand.js
packages/redux-query-react/index.d.ts
packages/redux-query-react/src/hooks/use-request-on-demand.js
packages/redux-query-react/src/hooks/use-request-on-demand.js.flow
packages/redux-query-react/src/index.js
packages/redux-query-react/test/hooks/use-request-on-demand.test.js

This PR introduces a hook that supports:
- Making GET requests on demand via React Hook
Previously, there was no way to send a GET request on demand via React Hook (outside of component render lifecycle).
The implementation is based off of `useMutation`. The main difference is that we are just dispatching `requestAsync` under the hood.

Introduce useRequestOnDemand hook

---

packages/redux-query-react/flow-test/hooks/use-request-on-demand.js
packages/redux-query-react/src/hooks/use-request-on-demand.js

Currently, if the callback to `useRequestOnDemand` is called while a request is in flight, the secondary callback will always return undefined. This update forces the query config to always force the request. Consumers can still control this behavior through their own query config.

Add `force: true` as a default for useRequestOnDemand callback

---

website/yarn.lock

As a push to resolve all critical/high vulns from dependencies in the redux-query repo, this PR updates:
- Docusaurus and peer deps
- Minimatch
How do I know this works?
Docs Website still builds and starts locally. Works correctly.

AMP-70918 upgrade docusaurus website dep

---

packages/redux-query-interface-superagent/yarn.lock
packages/redux-query-react/yarn.lock
yarn.lock

As a push to resolve all critical/high vulns from dependencies in the `redux-query` repo, this PR updates:
Babel and codecov `devDependencies`:
```sh
devDependencies
name                                       range   from       to      url
@babel/core                                ^7.0.1  7.10.4  ❯  7.21.0  https://babel.dev/docs/en/next/babel-core
@babel/plugin-proposal-object-rest-spread  ^7.4.4  7.10.4  ❯  7.20.7  https://babel.dev/docs/en/next/babel-plugin-proposal-object-rest-spread
@babel/preset-env                          ^7.0.0  7.10.4  ❯  7.20.2  https://babel.dev/docs/en/next/babel-preset-env
@babel/preset-flow                         ^7.0.0  7.10.4  ❯  7.18.6  https://babel.dev/docs/en/next/babel-preset-flow
@babel/preset-react                        ^7.0.0  7.10.4  ❯  7.18.6 …
```

[AMP-70918] update babel devDependencies

---

packages/redux-query-react/flow-test/hooks/use-request.js
packages/redux-query-react/src/components/connect-request.js
packages/redux-query/index.d.ts
packages/redux-query/src/actions/index.js
packages/redux-query/src/middleware/query.js
packages/redux-query/src/types.js

`customQueryMiddlewareConfig` is the same as middleware config, but it can be applied per request
**Does not have tests, so should be rolled out as RC deployment**

Add `customQueryMiddlewareConfig` to requests/mutations
